server:
  port: ${PORT:8091}
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cmps277"
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    javax:
      persistence:
        schema-generation:
          create-source: metadata
          scripts:
            action: drop-and-create
            create-target: create.sql